### ISSUE TITLE
Error in case when UserTask is after ServiceTask

### ISSUE THREAD

**Issue by rkichasov** [takari/bpm#15]
In flow start->service task -> user task -> end there is exception during serialization event to leveldb:
2017-10-17 15:04:09.592 ERROR 6740 --- [nio-8095-exec-2] i.t.b.leveldb.LevelDbPersistenceManager  : marshallValue -> error
java.io.NotSerializableException: takari.test.ServiceTaskRegistryImpl$1

There are 2 test cases in attachment.
First case pass:
start->user task -> service task -> end (test takari.test.Test#testPass)
Second case fail:
start->service task -> user task -> end (test takari.test.Test#testFail)

[takaritest.zip](https://github.com/takari/bpm/files/1391273/takaritest.zip)

**Comment by ibodrov** [comment]
Some time ago we added https://github.com/takari/bpm/commit/0c3a685aab8e6584905e3b3d871b59f517b996a7#diff-85d4db820e64dcbb19a3fded02642a8bR9
When enabled, it stores the result of a last expression evaluation as a context variable. Which in this case is a lambda instance.

This behavior can be safely disabled using
```
io.takari.bpm.Configuration cfg = new Configuration();
cfg.setStoreExpressionEvalResultsInContext(false);

Engine engine = new EngineBuilder().withConfiguration(cfg).build();
```
